[package]
name = "binance_us_and_global"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio             = { version = "1", features = ["full"] }
reqwest           = { version = "0.11", features = ["json", "rustls-tls"] }
tokio-socks       = "0.5"
tokio-tungstenite = { version = "0.20", features = ["rustls-tls-webpki-roots"] }
futures           = "0.3"
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
anyhow            = "1"
url               = "2"
